# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180928_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('filename', models.FileField(upload_to='media/images')),
            ],
        ),
        migrations.DeleteModel(
            name='audio_files',
        ),
    ]
