# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181001_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='title',
        ),
        migrations.AlterField(
            model_name='content',
            name='filename',
            field=models.FileField(upload_to='home/abohra/Documents/Dev/Django/musicbox/musicbox/add/media/images/'),
        ),
    ]
