# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181001_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='filename',
            new_name='files',
        ),
        migrations.AddField(
            model_name='content',
            name='album',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='content',
            name='art',
            field=models.ImageField(blank=True, default='', upload_to=b''),
        ),
        migrations.AddField(
            model_name='content',
            name='artist',
            field=models.CharField(blank=True, default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='content',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='content',
            name='mood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='content',
            name='movie',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='content',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
