# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181004_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='content',
            name='year',
        ),
        migrations.AlterField(
            model_name='content',
            name='files',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=b''),
        ),
    ]
